import React from "react";
import BgImage from "../assets/Images/FeatutresImg/bgimgg.png";
import Icon1 from "../assets/Images/FeatutresImg/svgone.png";
import Icon2 from "../assets/Images/FeatutresImg/svgtwo.png";
import Icon3 from "../assets/Images/FeatutresImg/svgthree.png";
import Icon4 from "../assets/Images/FeatutresImg/svgfour.png";
import Icon5 from "../assets/Images/FeatutresImg/svgfive.png";
import Icon6 from "../assets/Images/FeatutresImg/svgsix.png";

const Features = () => {
  const features = [
    {
      icon: Icon1,
      title: "Proactive blocklist tracking",
      description:
        "Be the first to know if your domain is added to a DNSBL such as those offered by Spamhaus with removal requests generated by Resend.",
    },
    {
      icon: Icon2,
      title: "Faster Time to Inbox",
      description:
        "Send emails from the region closest to your users. Reduce delivery latency with North American, South American, and European regions.",
    },
    {
      icon: Icon3,
      title: "Build confidence with BIMI",
      description:
        "Showcase your logo and company branding with BIMI. Receive guidance to obtain a VMC – the email equivalent of a checkmark on social media.",
    },
    {
      icon: Icon4,
      title: "Managed Dedicated IPs",
      description:
        "Get a fully managed dedicated IP that automatically warms up and autoscales based on your sending volume, no waiting period.",
    },
    {
      icon: Icon5,
      title: "Dynamic suppression list",
      description:
        "Prevent repeated sending to recipients who no longer want your email and comply with standards like the CAN-SPAM Act and others.",
    },
    {
      icon: Icon6,
      title: "IP and domain monitoring",
      description:
        "Monitor your DNS configuration for any errors or regressions. Be notified of any changes that could hinder your deliverability.",
    },
  ];

  return (
    <section className="relative  text-white px-6 py-16 md:px-12 lg:px-20 overflow-hidden">
      
      <img
        src={BgImage}
        alt="Background"
        className="absolute w-full h-full object-cover"
      />

      {/* Gradient Top Border */}
<div
  className="absolute md:mt-8 mt-0 left-1/2 transform -translate-x-1/2"
  style={{
    top: "0.5px",
    height: "1px",
    width: "90%",  
    maxWidth: "1600px",  
    background:
      "linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(143,143,143,0.67) 50%, rgba(0,0,0,0) 100%)",
  }}
></div>


      {/* Radial Gradient  */}
      <div
        className="absolute md:mt-2 mt-0 left-1/2 transform -translate-x-1/2"
        style={{
          top: "-80px",
          width: "280px",
          height: "200px",
          background:
            "radial-gradient(70.71% 70.71% at 50% 50%, rgba(200, 200, 200, 0.1) 0%, rgba(0, 0, 0, 0) 80%)",
        }}
      ></div>

      <div className="relative max-w-7xl mx-auto">
        
        <div className="mb-12 md:mt-0 mt-8 text-center lg:text-left">
          <h2 className="text-3xl md:text-4xl font-bold leading-tight font-[Inter]">
            Reach humans, <br />
            <span className="text-gray-400">not spam folders</span>
          </h2>
        </div>

        {/* Features */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-10">
          {features.map((feature, index) => (
            <div
              key={index}
              className="flex flex-col items-start text-left hover:scale-105 transition-transform duration-300"
            >
              <img
                src={feature.icon}
                alt={feature.title}
                className="w-6 h-6 object-contain mb-4"
              />
              <h3 className="text-lg font-semibold font-[Inter]">{feature.title}</h3>
              <p className="mt-2 text-sm text-gray-400">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
